//user info
CREATE TABLE SELF_USER(
     ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
     EMAIL VARCHAR(32) NOT NULL,
     PASSWORD VARCHAR(32) NOT NULL,
     FULLNAME VARCHAR(32) DEFAULT NULL,
     NICKNAME VARCHAR(32) DEFAULT NULL,
     CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     GENDER CHAR(5) DEFAULT NULL,
     BIRTHDAY DATE DEFAULT NULL,
     PHONE VARCHAR(32) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE UNIQUE INDEX unique_index_email on SELF_USER(EMAIL);
